name: Build and deploy a container to an Azure Web App

env:
  AZURE_WEBAPP_NAME: uspscio-casi-chatgpt   # set this to your application's name
  
on:
  push:
    branches:
      - main

permissions:
  contents: 'read'
  packages: 'write'
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to USPS container registry
        uses: docker/login-action@v2
        with:
          registry: casidevopenaicr001.azurecr.io
          username: ${{ secrets.CONTAINER_USERNAME }}
          password: ${{ secrets.CONTAINER_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./Dockerfile
          tags: |
            casidevopenaicr001.azurecr.io/chat:${{ github.sha }}

  deploy-casi-dev-openai-gen-rg-001:
    runs-on: ubuntu-latest

    needs: build

    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: 'casidevopenaicr001.azurecr.io/chat:${{ github.sha }}'
